knp_paginator:            # default number of items per page
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'   
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
        filtration: '@KnpPaginator/Pagination/filtration.html.twig' 